fix script

diff --git a/upload-logs/main b/upload-logs/main
--- a/upload-logs/main
+++ b/upload-logs/main
@@ -1,21 +1,67 @@
 #!/bin/bash
 
 ENDPOINT_URL="https://us-east1.watch.upstride.io/namespaces"
+MAXIMUM_LOGS=100
 
 function usage() {
-    echo -e "
-Usage:
+    echo -e \
+"Usage:
 
-  sudo upload_logs -u username -p password -c container_name -n namespace
+  sudo upload_logs -u username -p password -n namespace -i image_name [-d directory -c container_name]
 
   Retrieve and upload a docker container log to the specific endpoint <$ENDPOINT_URL>
   Arguments:
    - u: login's username
    - p: login's password or access token
+   - d: directory
    - c: container's name
+   - i: image's name
    - n: storage's namespace
   "
 }
+
+while getopts :h:u:p:c:n:i:d: flag
+do
+    case "${flag}" in
+        u) username=${OPTARG};;
+        p) password=${OPTARG};;
+        c) container_name=${OPTARG};;
+        i) imageName=${OPTARG};;
+        d) directory=${OPTARG};;
+        n) namespace=${OPTARG};;
+        h | *)
+          usage
+          exit 0
+          ;;
+    esac
+done
+
+# Find logs by container name, by container image or by folder
+function find_logs() {
+  local OPTIND
+  while getopts :d:i:c: opt
+  do
+      case "${opt}" in
+          d) directory=${OPTARG};;
+          c) container=${OPTARG};;
+          i) image=${OPTARG};;
+          *) ;;
+      esac
+  done
+  logfiles=()
+  #echo "i=$image,d=$directory,c=$container"
+  [ -n "$container" ] && \
+    container_id=$(docker inspect --format="{{.Id}}" "$container") && \
+    logfiles+=$(find /var/lib/docker/containers/"$container_id"/  -maxdepth 2 -name '*.log')
+  [ -n "$directory" ] && [ -d "$directory" ] &&\
+    logfiles+=$(find "$directory"  -maxdepth 2 -name '*.log')
+  [ -n "$image" ] &&\
+    short_uuid=$(docker ps --format {{.ID}} --filter "ancestor=$image") &&\
+    long_uuid=$(docker inspect --format="{{.Id}}" "$short_uuid")  &&\
+    logfiles+=$(find /var/lib/docker/containers/"$long_uuid"/  -maxdepth 2 -name '*.log')
+  echo "$logfiles"
+}
+
 
 #No arguments display usage
 [ $# == 0 ] && usage && exit 0
@@ -35,46 +81,75 @@ echo -e "\033[1;32m  step: check root privileges \033[0m"
 
 
 # read args
-while getopts u:p:c:n: flag
-do
-    case "${flag}" in
-        u) username=${OPTARG};;
-        p) password=${OPTARG};;
-        c) container_name=${OPTARG};;
-        n) namespace=${OPTARG};;
-    esac
-done
+
 
 echo -e "\033[1;32m  step: check arguments \033[0m"
 [ -z "$username" ] &&   { echo -e "\033[1;31m  x missing username \033[0m\n" && usage && exit 2; }
 [ -z "$password" ] &&   { echo -e "\033[1;31m  x missing password \033[0m\n" && usage && exit 2; }
-[ -z "$container_name" ] &&   { echo -e "\033[1;31m  x missing container_name \033[0m\n" && usage && exit 2; }
-[ -z "$namespace" ] &&   { echo -e "\033[1;31m  x missing storage_name \033[0m\n" && usage && exit 2; }
+[ -z "$container_name""$imageName""$directory" ] &&\
+   { echo -e "\033[1;31m  x missing one of directory, image_name or container_name \033[0m\n" && usage && exit 2; }
+[ -z "$namespace" ] &&  namespace="production"
 
 echo -e "\033[1;32m  step: check login \033[0m"
 code=$(curl -XPOST -u "$username:$password" --url "$ENDPOINT_URL/$namespace" \
       --write-out "%{http_code}\n" --silent --output /dev/null)
 [ "$code" -eq 401 ] &&  { echo -e "\033[1;31m  x wrong login username/password \033[0m\n" && exit 2; }
 
-echo -e "\033[1;32m  step: check container \033[0m"
-# shellcheck disable=SC2116
-container_id=$(docker inspect --format="{{.Id}}" "$container_name") && \
-logfiles=$(ls /var/lib/docker/containers/"$container_id"/*.log) \
-||  { echo -e "\033[1;31m  x container logs not found \033[0m\n" && exit 2; }
+echo -e "\033[1;32m  step: pushing log's files \033[0m"
+path=()
+STATUS="SUCCESS"
+declare -i total=0
 
-echo -e "\033[1;32m  step: pushing log's file \033[0m"
-path=logs/$(date '+%Y-%m-%d')/$container_name/$(date '+%H-%M')
-echo -e "\033[0;33m  + path: $namespace/$path \033[0m"
-for log in "${logfiles[@]}"; do
-  code=$(curl -XPOST -u "$username:$password" --url "$ENDPOINT_URL/$namespace/files/?path=$path" \
-        -F file=@"$log" --write-out "%{http_code}\n" --silent --output /dev/null)
-  [ "$code" -ne 200 ] &&  \
-  { echo -e "\033[1;31m  x something went wrong during upload: error_code=$code \033[0m\n"; } && \
-  STATUS=FAILED
-done
-echo -e "\033[0;33m  + status: SUCCESS \033[0m"
+if [ -n "$directory" ]; then
+  path=logs/$(date '+%Y-%m-%d')/raw/$(date '+%H-%M')
+  echo -e "\033[0;33m  + path: $namespace/$path \033[0m"
+  for log in $(find_logs -d "$directory"); do
+    code=$(curl -XPOST -u "$username:$password" --url "$ENDPOINT_URL/$namespace/files/?path=$path" \
+          -F file=@"$log" --write-out "%{http_code}\n" --silent --output /dev/null)
+    [ "$code" -ne 200 ] &&  \
+    { echo -e "\033[1;31m  x something went wrong during upload: log=$log \033[0m"; } && \
+    STATUS=FAILED ||\
+    total+=1
+    [ $total -gt $MAXIMUM_LOGS ] && break
+  done
+fi
+
+if [ -n "$container_name" ]; then
+  path=logs/$(date '+%Y-%m-%d')/docker/$container_name/$(date '+%H-%M')
+    echo -e "\033[0;33m  + source docker: $container_name \033[0m"
+  echo -e "\033[0;33m  + remote path: $namespace/$path \033[0m"
+  for log in $(find_logs -c "$container_name"); do
+    code=$(curl -XPOST -u "$username:$password" --url "$ENDPOINT_URL/$namespace/files/?path=$path" \
+          -F file=@"$log" --write-out "%{http_code}\n" --silent --output /dev/null)
+    [ "$code" -ne 200 ] &&  \
+    { echo -e "\033[1;31m  x something went wrong during upload: log=$log \033[0m"; } && \
+    STATUS=FAILED ||\
+    total+=1
+    [ $total -gt $MAXIMUM_LOGS ] && break
+  done
+fi
+
+if [ -n "$imageName" ]; then
+  path=logs/$(date '+%Y-%m-%d')/docker/$imageName/$(date '+%H-%M')
+  echo -e "\033[0;33m  + source docker: $imageName \033[0m"
+  echo -e "\033[0;33m  + remote path: $namespace/$path \033[0m"
+  for log in $(find_logs -i "$imageName"); do
+    code=$(curl -XPOST -u "$username:$password" --url "$ENDPOINT_URL/$namespace/files/?path=$path" \
+          -F file=@"$log" --write-out "%{http_code}\n" --silent --output /dev/null)
+    [ "$code" -ne 200 ] &&  \
+    { echo -e "\033[1;31m  x something went wrong during upload: log=$log \033[0m"; } && \
+    STATUS=FAILED ||\
+    total+=1
+    [ $total -gt $MAXIMUM_LOGS ] && break
+  done
+fi
+
+echo -e "\033[0;33m  + total: $total \033[0m"
+[ $STATUS == "SUCCESS" ] && echo -e "\033[0;33m  + status: $STATUS \033[0m" ||
+  echo -e "\033[0;31m  + status: $STATUS \033[0m"
 
 echo  -e "\033[1;33m *** exit\n" && exit 0
+
 
 
 
